using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.

[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("open.imaging.S3TC")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("99573afc-de2f-47fa-9cc7-a79561ffbd5b")]

// emit as fileversion description
[assembly: AssemblyTitle(MakeVersion.MAKEVERSION_DESC)]
[assembly: AssemblyDescription(MakeVersion.MAKEVERSION_DESC)]
// emit as fileversion copyright
[assembly: AssemblyCopyright(MakeVersion.MAKEVERSION_COPYRIGHT)]
// emit as assembly version
[assembly: AssemblyVersion(MakeVersion.MAKEVERSION_PRODUCT)]
// emit as file 'Product version'
[assembly: AssemblyInformationalVersion(MakeVersion.MAKEVERSION_PRODUCT)]
// emit as file 'File version'
[assembly: AssemblyFileVersion(MakeVersion.MAKEVERSION_FILE)]

//
// this file content is autogenerated by MakeVersion.exe tool
//
// NOTICE:
// If you increment the AssemblyVersion, any project that uses your dll will need to be re-compiled. 
// However, if you keep the AssemblyVersion the same and increment the AssemblyFileVersion by itself, 
// then you can swap the new dll in without having to re-compile whatever is using it. 
// NOTICE: file version (major.minor.build.revision) is automatically incrementing revision number.
//<!-- Needed by MakeVersion to process file before build -->
//<!-- only known problem is if file kept open in IDE it will use loaded copy instead of newly generated content -->
//<Target Name="BeforeBuild">
//  <PropertyGroup>
//    <PreBuildEvent>
//      %(ProjectDir)Properties\MakeVersion.exe -i:r -s:%(ProjectDir)Properties\MakeVersion.cs
//    </PreBuildEvent>
//  </PropertyGroup>
//</Target>
class MakeVersion
{
  private const string MAKEVERSION_MAJOR            = "0";
  private const string MAKEVERSION_MINOR            = "YEAR2";
  private const string MAKEVERSION_BUILD            = "MONTHDAY";
  private const string MAKEVERSION_REVISION         = "%(SVN)";

  private const string MAKEVERSION_FILE_FORMAT      = "%(MAJOR).%(SVN).%(MINOR).%(BUILD)";
  public const string MAKEVERSION_FILE              = "0.53.18.1111";

  private const string MAKEVERSION_PRODUCT_FORMAT   = "%(MAJOR).%(SVN)";
  public const string MAKEVERSION_PRODUCT           = "0.53";
  
  // custom filters
  private const string MAKEVERSION_COPYRIGHT_FORMAT = "Copyright © %(YEAR) Nikola Bozovic";
  public const string MAKEVERSION_COPYRIGHT         = "Copyright © 2018 Nikola Bozovic";

  private const string MAKEVERSION_DESC_FORMAT      = "open.imaging.S3TC library (svn:%(SVN))";
  public const string MAKEVERSION_DESC              = "open.imaging.S3TC library (svn:53)";
}
